language: python
python:
  - "3.4"
  - "2.7"
virtualenv:
   system_site_packages: True
before_install:
  - sudo apt-get install -y python-dbus python3-dbus python-pyside.qtcore python3-pyside.qtcore
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
# command to run tests, e.g. python setup.py test
script:
  - python sbin/yarfictl --help
