#!/usr/bin/env python

# YARFI - Yet Another Replacement For Init
# Copyright (C) 2014 Niklas Sombert
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os
import sys
import subprocess
args = {"os": os, "sys": sys, "subprocess": subprocess}

modules = []

wanted_target = ""
cmdline = open("/proc/cmdline")
for line in cmdline:
	args = line.split(" ")
	for x in args:
		z = x.split("=")
		if z[0] == "yarfi-target":
			wanted_target = z[1]
cmdline.close()
if wanted_target == "":
	wanted_target = "default"

def reach_target(target):
	os.chdir("/etc/yarfi/targets")
	Target = __import__(wanted_target).target()
	for conflict in Target.conflicts:
		for module in modules:
			if conflict == module.__name__:
				stop(conflict)
	remaining_dependencies = Target.depends
	for module in modules:
		for dependency in remaining_dependencies:
			if module.__name__ == dependency:
				remaining_dependencies.remove(dependency)
	for dependency in remaining_dependencies:
		start(dependency)

reach_target(wanted_target)